#!/usr/bin/env python3
"""
Apply an RL trick to a target benchmark repo.

The default custom_jax / custom_torch / sb3 templates are TRICK-FREE — every
trick lives entirely under ${CLAUDE_PLUGIN_ROOT}/knowledge/templates/rl-tricks/<name>/
as:
    manifest.yaml  → name, description, supported algorithms, refs/caveats
    patches.yaml   → file_patches[] (literal find/replace edits) +
                     config_patches[] (yaml key=value flips on parallel.yaml)

Apply:
    python apply_trick.py --trick obs_rms_jax  --algorithm ppo --repo /abs/path
    python apply_trick.py --trick reward_norm_jax            --repo /abs/path

If --algorithm is omitted, every algorithm in the manifest's `algorithms` list
is targeted (config_patches loop over `{algo}` substitution).

Idempotency:
    File patches: re-running consumes nothing once the `find` block has been
    replaced. Each edit reports `[noop]` instead of erroring.
    Config patches: same — already-applied flag values are reported `[noop]`.

Exit codes:
    0 = patched (or all-noop), 2 = bad inputs / not found / patch failed.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _plugin_root(override: str | None) -> Path:
    if override:
        return Path(override).resolve()
    # See list_tricks.py: the env var is deliberately not consulted.
    return Path(__file__).resolve().parents[2]   # <plugin>/scripts/rl-tricks/<this>.py


def _algorithm_slug(repo: Path) -> str:
    """Read harbor/rl-integration-generator/rl-suite-spec.json:algorithm_source.slug.

    Falls back to `custom_jax` if the spec is missing — but warns. The repo
    is expected to have been generated by rl-integration-generator first.
    """
    import json
    spec = repo / "harbor" / "rl-integration-generator" / "rl-suite-spec.json"
    if not spec.is_file():
        print(f"[warn] {spec} not found — defaulting algorithm slug to 'custom_jax'.",
              file=sys.stderr)
        return "custom_jax"
    data = json.loads(spec.read_text())
    src = data.get("algorithm_source", {})
    return str(src.get("slug") or src.get("kind") or "custom_jax")


def _read_block(trick_dir: Path, ref) -> str:
    """A block in patches.yaml is either:
       - an inline string (literal text), OR
       - a path (string) relative to the trick dir, pointing at a file with the raw text.
    """
    if not isinstance(ref, str):
        return str(ref)
    candidate = (trick_dir / ref).resolve()
    if candidate.is_file():
        return candidate.read_text()
    # Treat as inline literal otherwise.
    return ref


def _apply_file_patches(file_patches, repo: Path, slug: str, trick_dir: Path,
                        dry_run: bool) -> tuple[int, int, int]:
    """Apply each find/replace edit. Returns (changed, noop, errors)."""
    n_changed = n_noop = n_err = 0
    for fp in file_patches or []:
        rel = str(fp["file"]).format(slug=slug)
        target = repo / rel
        if not target.is_file():
            print(f"[error] {rel} not found in repo (rendered scaffold missing?)",
                  file=sys.stderr)
            n_err += len(fp.get("edits", []))
            continue
        text = target.read_text()
        for edit in fp.get("edits", []):
            edit_id = edit.get("id", "<unnamed>")
            find = _read_block(trick_dir, edit["find"])
            replace = _read_block(trick_dir, edit["replace"])
            if find == replace:
                print(f"[skip] {rel}::{edit_id} (find == replace, no-op definition)")
                n_noop += 1
                continue
            n_find = text.count(find)
            n_replaced_already = text.count(replace)
            if n_find == 0:
                # Already replaced (or never matched). Distinguish via the
                # presence of the post-trick string.
                if n_replaced_already >= 1:
                    print(f"[noop] {rel}::{edit_id} (already applied)")
                    n_noop += 1
                else:
                    print(f"[error] {rel}::{edit_id} — find block not present "
                          f"and replace block not present either. Manual inspection needed.",
                          file=sys.stderr)
                    n_err += 1
                continue
            if n_find > 1:
                print(f"[error] {rel}::{edit_id} — find block matches {n_find} "
                      f"times; refusing to apply (ambiguous). Tighten the find context.",
                      file=sys.stderr)
                n_err += 1
                continue
            # Exactly one match.
            if dry_run:
                print(f"[dry-run] {rel}::{edit_id} would replace 1 occurrence")
            else:
                text = text.replace(find, replace, 1)
                print(f"[patched] {rel}::{edit_id}")
            n_changed += 1
        if not dry_run and n_changed:
            target.write_text(text)
    return n_changed, n_noop, n_err


def _apply_config_patches(config_patches, repo: Path, target_algos: list[str], dry_run: bool):
    """Add/flip yaml keys in parallel.yaml configs. Preserves comments via ruamel."""
    try:
        import yaml
    except ImportError:
        print("[error] PyYAML required (pip install pyyaml)", file=sys.stderr)
        return 0, 0, 1
    try:
        from ruamel.yaml import YAML
        ruamel = YAML(); ruamel.preserve_quotes = True; ruamel.indent(mapping=2, sequence=4, offset=2)
        load = lambda p: ruamel.load(p.read_text())
        dump = lambda data, p: (lambda fh: ruamel.dump(data, fh))(open(p, "w"))
        engine = "ruamel.yaml (comments preserved)"
    except ImportError:
        load = lambda p: yaml.safe_load(p.read_text())
        dump = lambda data, p: p.write_text(yaml.safe_dump(data, sort_keys=False))
        engine = "PyYAML (comments stripped — install ruamel.yaml to preserve)"

    n_changed = n_noop = n_err = 0
    for patch in config_patches or []:
        for algo in target_algos:
            rel = str(patch["file"]).format(algo=algo)
            target = repo / rel
            if not target.is_file():
                print(f"[warn] {rel} not found — skip", file=sys.stderr); continue
            data = load(target)
            if data is None:
                print(f"[warn] {rel} empty/unparseable — skip", file=sys.stderr); continue
            key = patch["key"]; value = patch["value"]
            cur = data.get(key) if isinstance(data, dict) else None
            if cur == value:
                print(f"[noop] {rel}: {key}={value} (already)")
                n_noop += 1; continue
            if dry_run:
                print(f"[dry-run] {rel}: {key}: {cur!r} -> {value!r}")
            else:
                data[key] = value
                dump(data, target)
                print(f"[patched] {rel}: {key}={value} (was {cur!r})")
            n_changed += 1
    return n_changed, n_noop, n_err, engine


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--trick", required=True)
    p.add_argument("--algorithm", default=None,
                   help="ppo / sac / td3; if omitted, applies to every algo in manifest")
    p.add_argument("--repo", required=True, type=Path)
    p.add_argument("--plugin-root", default=None)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    repo: Path = args.repo.resolve()
    if not repo.is_dir():
        print(f"[error] repo not a directory: {repo}", file=sys.stderr); return 2

    root = _plugin_root(args.plugin_root)
    trick_dir = root / "knowledge" / "templates" / "rl-tricks" / args.trick
    manifest_path = trick_dir / "manifest.yaml"
    patches_path = trick_dir / "patches.yaml"
    if not manifest_path.is_file():
        avail = sorted([d.name for d in (root / "knowledge" / "templates" / "rl-tricks").iterdir()
                        if d.is_dir()]) if (root / "knowledge" / "templates" / "rl-tricks").is_dir() else []
        print(f"[error] no trick named {args.trick!r}. Available: {avail}",
              file=sys.stderr); return 2

    try:
        import yaml
    except ImportError:
        print("[error] PyYAML required (pip install pyyaml)", file=sys.stderr); return 2

    manifest = yaml.safe_load(manifest_path.read_text())
    if patches_path.is_file():
        patches = yaml.safe_load(patches_path.read_text()) or {}
    else:
        # Backwards compat: older tricks stored config_patches directly in manifest.
        patches = {"config_patches": manifest.get("config_patches") or []}

    # --- Applicability gate: enforce explicit `backend` + `algorithms` fields. ---
    # The manifest MUST declare both. If they're missing, the trick author hasn't
    # told us what it applies to and we refuse to apply blindly.
    declared_backend = manifest.get("backend")
    algos_supported = list(manifest.get("algorithms") or [])
    if not declared_backend:
        print(f"[error] trick {args.trick!r} manifest is missing the `backend` field "
              f"(must be one of: custom_torch, custom_jax, stable_baseline3, "
              f"local_implementation). Refusing to apply blindly.",
              file=sys.stderr); return 2
    if not algos_supported:
        print(f"[error] trick {args.trick!r} manifest is missing the `algorithms` list "
              f"(must list at least one of: ppo, sac, td3). Refusing to apply blindly.",
              file=sys.stderr); return 2

    # Match manifest.backend to the user's repo's algorithm_source.kind|slug.
    slug = _algorithm_slug(repo)
    if str(declared_backend) != str(slug):
        print(f"[error] trick {args.trick!r} declares backend={declared_backend!r} "
              f"but this repo's harbor/rl-integration-generator/rl-suite-spec.json says "
              f"algorithm_source.slug={slug!r}. The trick's edits target the "
              f"{declared_backend} tree's file layout — applying them to "
              f"{slug} would either no-op (find blocks miss) or corrupt the "
              f"wrong file. Re-run rl-integration-generator with the matching "
              f"source, or pick a {slug}-flavored trick (e.g. "
              f"obs_rms_torch instead of obs_rms_jax).",
              file=sys.stderr); return 2

    # Target algorithms. --algorithm narrows the loop; otherwise iterate manifest's list.
    if args.algorithm is not None:
        if args.algorithm not in algos_supported:
            print(f"[error] trick {args.trick!r} does not support algorithm "
                  f"{args.algorithm!r}. Supported: {algos_supported}",
                  file=sys.stderr); return 2
        target_algos = [args.algorithm]
    else:
        target_algos = algos_supported

    print(f"[apply] trick={args.trick}  backend={declared_backend}  algos={target_algos}  slug={slug}  repo={repo}")

    file_patches = patches.get("file_patches") or []
    config_patches = patches.get("config_patches") or []

    if not file_patches and not config_patches:
        print(f"[warn] trick {args.trick!r} has no patches — nothing to do",
              file=sys.stderr); return 0

    fp_changed, fp_noop, fp_err = _apply_file_patches(file_patches, repo, slug, trick_dir, args.dry_run)
    cp_changed, cp_noop, cp_err, yaml_engine = _apply_config_patches(
        config_patches, repo, target_algos, args.dry_run)

    print(f"\nDone. file_patches: changed={fp_changed} noop={fp_noop} err={fp_err}")
    print(f"      config_patches: changed={cp_changed} noop={cp_noop} err={cp_err}")
    print(f"      (yaml engine: {yaml_engine})")
    if args.dry_run:
        print("(dry run; no files modified)")
    return 0 if (fp_err + cp_err) == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
